# Generated by Django 4.0.3 on 2022-08-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Общее количество товаров')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая Цена')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trousers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('max_size', models.SmallIntegerField(blank=True, null=True, verbose_name='Максимальный размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Overalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('max_size', models.SmallIntegerField(blank=True, null=True, verbose_name='Максимальный размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размер')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Рост')),
                ('size_of_rud', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Обхват груди')),
                ('size_of_waist', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Обхват талии')),
                ('size_of_hips', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Обхват бедер')),
                ('color', models.CharField(blank=True, choices=[(None, 'Не выбран'), ('Mint', 'Мята'), ('Blue', 'Голубой'), ('Graphite', 'Графит'), ('White', 'Белый'), ('Dark Blue', 'Темно-синий')], max_length=50, null=True, verbose_name='Цвет')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество товара одного вида')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name=' Общая Цена')),
                ('object_id', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_products', to='mainapp.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.cartproduct'),
        ),
        migrations.CreateModel(
            name='Blouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара')),
                ('max_size', models.SmallIntegerField(blank=True, null=True, verbose_name='Максимальный размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
