# Generated by Django 4.0.3 on 2022-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blouse',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='overalls',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='trousers',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
    ]
